Update Jenkinsfile

diff --git a/spring-petclinic/Jenkinsfile b/spring-petclinic/Jenkinsfile
--- a/spring-petclinic/Jenkinsfile
+++ b/spring-petclinic/Jenkinsfile
@@ -1,20 +1,16 @@
 pipeline {
-    agent none
-
+    agent any
     tools {
         maven 'm3'
     }
-
     environment {
-        GKE_CLUSTER_NAME = 'prod-phase-sonar'
-        GKE_PROJECT = 'burner-mankomma'
+        GKE_CLUSTER_NAME = 'jenkins-cd'
+        GKE_PROJECT = 'phrasal-verve-447910-d9'
         GKE_ZONE = 'us-central1-a'
         DOCKER_REGISTRY = 'docker.io/rohith9769'
         DOCKER_IMAGE_NAME = 'pet-image'
-        SONARQUBE_URL = 'https://34.121.131.107:9000'
-        SONARQUBE_TOKEN = credentials('jenkins-sonar')
+        FULL_IMAGE_PATH = "${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:v1"
     }
-
     stages {
         stage('Clone Repository') {
             agent {
@@ -54,7 +50,7 @@ spec:
                 checkout scm
             }
         }
-
+ 
         stage('Build') {
             agent {
                 kubernetes {
@@ -99,52 +95,7 @@ spec:
                 }
             }
         }
-
-        stage('SonarQube Analysis') {
-            agent {
-                kubernetes {
-                    label 'petclinic-pod'
-                    defaultContainer 'maven'
-                    yaml '''
-apiVersion: v1
-kind: Pod
-metadata:
-  name: petclinic-pod
-spec:
-  containers:
-    - name: maven
-      image: maven:3.8.3-openjdk-17
-      command:
-        - cat
-      tty: true
-    - name: docker
-      image: docker:19.03.12
-      privileged: true
-      command:
-        - cat
-      tty: true
-  '''
-                }
-            }
-            steps {
-                container('maven') {
-                    script {
-                        dir('spring-petclinic') {
-                            withSonarQubeEnv('jenkins-sonar') {
-                                sh """
-                                    mvn sonar:sonar \
-                                    -Dsonar.projectKey=sonartest \
-                                    -Dsonar.projectName="sonartest" \
-                                    -Dsonar.host.url=${SONARQUBE_URL} \
-                                    -Dsonar.login=${SONARQUBE_TOKEN}
-                                """
-                            }
-                        }
-                    }
-                }
-            }
-        }
-
+ 
         stage('Build Docker Image') {
             agent {
                 kubernetes {
@@ -181,11 +132,84 @@ spec:
             }
             steps {
                 container('docker') {
-                    sh "docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:v1 ."
+                    script {
+                        dir('spring-petclinic') {
+                            sh "docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:v1 -f Dockerfile ."
+                        }
+                    }
                 }
             }
         }
-
+ 
+        stage('Run Trivy Scan') {
+            agent {
+                kubernetes {
+                    label 'petclinic-pod'
+                    defaultContainer 'docker'
+                    yaml '''
+apiVersion: v1
+kind: Pod
+metadata:
+  name: petclinic-pod
+spec:
+  containers:
+    - name: docker
+      image: docker:19.03.12
+      privileged: true
+      command:
+        - cat
+      tty: true
+      volumeMounts:
+        - name: docker-socket
+          mountPath: /var/run/docker.sock
+  volumes:
+    - name: docker-socket
+      hostPath:
+        path: /var/run/docker.sock
+        type: Socket
+'''
+                }
+            }
+            steps {
+                sh '''
+                    # Install curl if missing
+                    apk add --no-cache curl
+ 
+                    # Install Trivy
+                    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin
+ 
+                    # Ensure Trivy is in the PATH
+                    export PATH=$PATH:$(pwd)/bin
+ 
+                    # Verify Trivy installation
+                    if ! command -v trivy &> /dev/null; then
+                        echo "Trivy could not be found, exiting..."
+                        exit 1
+                    fi
+ 
+                    # Download the HTML template for Trivy reports
+                    curl -O https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
+ 
+                    # Run Trivy scan and generate the HTML report using the template
+                     curl -O https://github.com/MeghanaMeghas/pipeline/blob/main/spring-petclinic/custom-html.tpl
+                    trivy image --severity HIGH,CRITICAL --format template --template "@custom-html.tpl" -o trivy-scan-report.html ${FULL_IMAGE_PATH}
+                '''
+            }
+            post {
+                always {
+                    echo "Publishing Trivy Scan Report..."
+                    publishHTML([
+                        allowMissing: false,
+                        alwaysLinkToLastBuild: true,
+                        keepAll: true,
+                        reportDir: '.',
+                        reportFiles: 'trivy-scan-report.html',
+                        reportName: 'Trivy Vulnerability Report'
+                    ])
+                }
+            }
+        }
+ 
         stage('Push Docker Image to Docker Hub') {
             agent {
                 kubernetes {
@@ -222,12 +246,12 @@ spec:
                 }
             }
         }
-
+ 
         stage('Deploy to GKE') {
             agent {
                 kubernetes {
                     label 'petclinic-pod'
-                    defaultContainer 'docker'
+                    defaultContainer 'gcloud'
                     yaml '''
 apiVersion: v1
 kind: Pod
@@ -235,6 +259,11 @@ metadata:
   name: petclinic-pod
 spec:
   containers:
+    - name: gcloud
+      image: google/cloud-sdk:latest
+      command:
+        - cat
+      tty: true
     - name: docker
       image: docker:19.03.12
       privileged: true
@@ -253,10 +282,10 @@ spec:
                 }
             }
             steps {
-                container('docker') {
+                container('gcloud') {
                     sh "gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} --zone ${GKE_ZONE} --project ${GKE_PROJECT}"
-                    sh 'kubectl apply -f k8s/deployment.yaml'
-                    sh 'kubectl apply -f k8s/service.yaml'
+                    sh 'kubectl apply -f spring-petclinic/k8s/deployment.yaml'
+                    sh 'kubectl apply -f spring-petclinic/k8s/service.yaml'
                 }
             }
         }
